#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CYCLE="${ROOT}/scripts/run_discovery_cycle.sh"

sandbox() {
  local d; d="$(mktemp -d)"
  mkdir -p "$d/state/inbox/processed" "$d/runs" "$d/discoveries" "$d/ref" "$d/logs" "$d/af"
  printf '>ref\nMKTAYIAKQR\n' > "$d/ref/ref.fasta"
  printf '{"diskFloorGB":0,"maxCandidates":20,"maxWorkspaceBytes":1073741824000,"maxLogFiles":200,"budgetSeconds":60,"maxConsecutiveFailures":5,"throttleSeconds":300,"maxDaemonLogBytes":10485760,"enableNetwork":false,"fetchPageSize":5,"fetchRateLimitSeconds":0,"uniprotHost":"rest.uniprot.org"}' > "$d/worker.json"
  echo "$d"
}
run() {
  STATE_DIR="$1/state" RUNS_DIR="$1/runs" DISCOVERIES_DIR="$1/discoveries" \
  REFERENCE="$1/ref/ref.fasta" LOG_DIR="$1/logs" NOTIFY_CMD="true" \
  CONFIG="$1/worker.json" PIPELINE_CMD="bash ${ROOT}/Tests/perpetual/fake_pipeline.sh" \
  ALPHAFOLD_CACHE="$1/af" bash "$CYCLE"
}

# a normal cycle must (re)generate the dashboard
S="$(sandbox)"; printf '>TESTACC1\nMKTAYIAKQR\n' > "$S/state/inbox/b.fasta"; run "$S"
[[ -f "$S/discoveries/dashboard.html" ]] || { echo "FAIL: dashboard not generated by cycle"; exit 1; }
grep -qi 'BioLab Perpetual Discovery' "$S/discoveries/dashboard.html" || { echo "FAIL: dashboard content missing"; exit 1; }

# vendor script exists and refuses network without opt-in
VEND="${ROOT}/scripts/vendor_assets.sh"
[[ -x "$VEND" ]] || { echo "FAIL: vendor_assets.sh missing/not executable"; exit 1; }
set +e; DISCOVERIES_DIR="$S/discoveries" bash "$VEND" >/dev/null 2>&1; rc=$?; set -e
[[ "$rc" -ne 0 ]] || { echo "FAIL: vendor should refuse without ALLOW_NETWORK"; exit 1; }
[[ ! -f "$S/discoveries/assets/3Dmol-min.js" ]] || { echo "FAIL: vendor fetched without opt-in"; exit 1; }

echo "dashboard cycle tests OK"
